on:
    push:
        branches:
            - main

jobs:
    integration-delivery:
        runs-on: ubuntu-latest
        environment: Test
        container:
            image: node
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              working-directory: BDE
              run: npm install 

            - name: Build website
              working-directory: BDE
              run: npm run build
            
            - name: FTP delivery
              uses: SamKirkland/FTP-Deploy-Action@4.3.3
              with:
                  server: ${{ vars.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  server-dir: test/todo/ 
                  local-dir: BDE/dist/ 
            
            - name: List files
              run: ls -R

            - name: Install TestCafe
              run: npm install -g testcafe

            - name: Update APT
              run: apt-get update

            - name: Install Chromium
              run: apt-get install -y chromium
            
            - name: Run tests
              working-directory: BDE
              run: testcafe chromium:headless test/todo-app.js
            
            - name: Store artifacts
              uses: actions/upload-artifact@v4  # Updated to v4
              with:
                  name: dist
                  path: BDE/dist/
    
    deployment:
        needs: integration-delivery
        runs-on: ubuntu-latest
        environment: Live
        steps:
            - name: Load artifacts
              uses: actions/download-artifact@v4  # Updated to v4
              with:
                  name: dist
                  path: BDE/dist/  # Adjusted path

            - name: Ensure /dist directory exists
              run: |
                  if [ ! -d "BDE/dist" ]; then
                    echo "/dist directory not found!"
                    exit 1
                  fi

            - name: FTP deploy
              uses: SamKirkland/FTP-Deploy-Action@4.3.3
              with:
                  server: ${{ vars.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  server-dir: live/todo/ 
                  local-dir: BDE/dist/ 
            