name: TeamWorkflow

on:
  push:
    branches:
      - main

jobs:
  integration-delivery:
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install 

      - name: Build website
        run: npm run build

      - name: SFTP delivery
        uses: appleboy/scp-action@master
        with:
          host: ssh.sunguard.dk
          username: ${{ secrets.FTP_USERNAME }}  # Set in GitHub secrets
          password: ${{ secrets.FTP_PASSWORD }}  # Set in GitHub secrets
          port: 22  # Port for SFTP
          source: "dist/*"  # Adjust based on your build output
          target: "/path/on/server/test/todo/"  # Adjust this to the correct target directory

      - name: List files
        run: ls -R

      - name: Install TestCafe
        run: npm install -g testcafe

      - name: Update APT
        run: sudo apt-get update

      - name: Install Chromium
        run: sudo apt-get install -y chromium

      - name: Run tests
        run: testcafe chromium:headless test/todo-app.js

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deployment:
    needs: integration-delivery
    runs-on: ubuntu-latest
    steps:
      - name: Load artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Ensure /dist directory exists
        run: |
          if [ ! -d "dist" ]; then
            echo "/dist directory not found!"
            exit 1
          fi

      - name: SFTP deploy
        uses: appleboy/scp-action@master
        with:
          host: ssh.sunguard.dk
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "dist/*"
          target: "/path/on/server/live/"  # Adjust this for your live directory
