name: TeamWorkflow

on:
  push:
    branches:
      - main

jobs:  # Use 'jobs' instead of 'job'
  integration-delivery:
    runs-on: ubuntu-latest
    environment: Test
    container:
      image: node
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: Start development server
        run: npm run dev &
        env:
          HOST: localhost
          PORT: 5173  # Ensure this matches the port used in your tests

      - name: Wait for server to be ready
        run: |
          until curl -s http://localhost:5173; do
            echo "Waiting for server..."
            sleep 3
          done

      - name: Install TestCafe
        run: npm install -g testcafe

      - name: Run tests
        run: testcafe chromium:headless test/*.testcafe.ts

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/



  deployment:
    needs: integration-delivery
    runs-on: ubuntu-latest
    environment: Live
    steps:
      - name: Load artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
      - name: FTP deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: live/todo/
          local-dir: dist/

