name: TeamWorkflow

on:
  push:
    branches:
      - main

jobs:  # Use 'jobs' instead of 'job'
  integration-delivery:  # Job name
    runs-on: ubuntu-latest
    environment: Test  # Corrected spelling
    container:
      image: node
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: FTP delivery
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: test/todo/
          local-dir: dist/  # Ensure this points to the correct build output directory
