name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  integration-delivery:
    runs-on: ubuntu-latest
    environment: Test
    container:
      image: node
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          
      - name: Install dependencies
        run: npm install
        
      - name: Build website
        run: npm run build
        
        - name: SFTP delivery
        uses: appleboy/scp-action@master
        with:
        host: ssh.sunguard.dk
        username: sunguard.dk
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 22
        source: "./dist/*"  # This is the local path to your files
        target: "/home/sunguard.dk/public_html/test/todo/"  # Adjust this to your server path
          
      - name: Install TestCafe
        run: npm install -g testcafe
        
      - name: Update APT
        run: |
          apt-get update
          apt-get install -y chromium
          
      - name: Run tests
        run: testcafe chromium:headless test/todo-app.js
        
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/

  deployment:
    needs: integration-delivery
    runs-on: ubuntu-latest
    environment: Live
    steps:
      - name: Load artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist/
          
      - name: Ensure /dist directory exists
        run: |
          ls -la
          if [ ! -d "dist" ]; then
            echo "/dist directory not found!"
            exit 1
          fi
          
      - name: SFTP delivery
        uses: appleboy/scp-action@master
        with:
        host: ssh.sunguard.dk
        username: sunguard.dk
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 22
        source: "./dist/*"  # This is the local path to your files
        target: "/home/sunguard.dk/public_html/test/todo/"  # Adjust this to your server path

