name: TeamWorkflow

on:
  push:
    branches:
      - main  # Ensure this matches the branch you want to push to

jobs:
  integration-delivery:
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install 

      - name: Build website
        run: npm run build

      - name: FTP delivery
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}  # Ensure this is correctly set in your secrets
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: test/todo/  # Change as necessary
          local-dir: dist/  # Make sure this matches your build output location

      - name: List files
        run: ls -R

      - name: Install TestCafe
        run: npm install -g testcafe

      - name: Update APT
        run: sudo apt-get update

      - name: Install Chromium
        run: sudo apt-get install -y chromium

      - name: Run tests
        run: testcafe chromium:headless test/todo-app.js

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deployment:
    needs: integration-delivery
    runs-on: ubuntu-latest
    steps:
      - name: Load artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Ensure /dist directory exists
        run: |
          if [ ! -d "dist" ]; then
            echo "/dist directory not found!"
            exit 1
          fi

      - name: FTP deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}  # Ensure this is correct
          username: ${{ secrets.FTP_USERNAME }}  # Ensure this is correct
          password: ${{ secrets.FTP_PASSWORD }}  # Ensure this is correct
          server-dir: live/todo/  # Change as necessary
          local-dir: dist/
