name: TeamWorkflow

on:
  push:
    branches:
      - main

jobs:
  integration-delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install 

      - name: Build website
        run: npm run build

      - name: SFTP delivery
        uses: appleboy/scp-action@master
        with:
          host: ssh.sunguard.dk
          username: ${{ secrets.FTP_USERNAME }}  # Set in GitHub secrets
          password: ${{ secrets.FTP_PASSWORD }}  # Set in GitHub secrets
          port: 22  # Port for SFTP
          source: "dist/*"  # Adjust based on your build output
          target: "/var/www/html/todo-app/"

      - name: List files
        run: ls -R

  run-tests:
    runs-on: ubuntu-latest
    needs: integration-delivery
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install TestCafe
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium
          npm install -g testcafe

      - name: Run tests
        run: testcafe chromium:headless test/todo-app.js

      - name: Store artifacts
        run: |
          echo "Checking if dist directory exists..."
          if [ -d "dist" ]; then
            echo "Uploading dist artifacts..."
            tar -czf dist.tar.gz dist/  # Create a tarball of the dist directory
            echo "Uploading artifacts..."
            echo "Uploading dist artifacts..."
            echo "dist.tar.gz" > dist-files.txt
          else
            echo "/dist directory not found!"
            exit 1
          fi

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist.tar.gz

  deployment:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Load artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./  # Download to the current working directory

      - name: Ensure dist.tar.gz exists
        run: |
          if [ ! -f "dist.tar.gz" ]; then
            echo "dist.tar.gz not found!"
            exit 1
          fi

      - name: Extract artifacts
        run: |
          tar -xzf dist.tar.gz  # Extract the downloaded tarball

      - name: Ensure /dist directory exists
        run: |
          if [ ! -d "dist" ]; then
            echo "/dist directory not found!"
            exit 1
          fi

      - name: SFTP deploy
        uses: appleboy/scp-action@master
        with:
          host: ssh.sunguard.dk
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "dist/*"
          target: "/var/www/html/todo-app/"
